#!/bin/bash

musicplayer="moc"
#musicplayer="audacious"

/usr/bin/nitrogen --restore &

if [[ "$musicplayer" == "audacious" ]]; then
	# kill audacious if it's already running
	if killall -0 audacious > /dev/null 2>&1; then
		killall -9 audacious
	fi
	/usr/bin/audacious --headless &
fi

currentmusic() {
	if [[ "$musicplayer" == "audacious" ]]; then
		# make sure audacious is actually running before doing anything
		if ! killall -0 audacious > /dev/null 2>&1; then
			echo "Stopped - --/--"
			return
		fi

		trackname=$(/usr/bin/audtool --current-song)
		time="$(audtool --current-song-output-length)/$(audtool --current-song-length)"

		if $(/usr/bin/audtool --playback-playing); then status="$time"; fi
		if $(/usr/bin/audtool --playback-paused); then status="**${time}**"; fi
		if $(/usr/bin/audtool --playback-stopped); then echo "Stopped - --/--"; return; fi
	fi

	if [[ $musicplayer == "moc" ]]; then
		if ! /usr/bin/mocp -i > /dev/null 2>&1; then
			/usr/bin/mocp -S > /dev/null 2>&1
		fi
		case $(mocp -i | grep "^State:" | awk '{print $2}') in
			STOP)
				echo "Stopped - --/--"
				return
				;;
			PLAY)
				status=$(/usr/bin/mocp -Q "%ct/%tt")
				;;
			PAUSE)
				status=$(/usr/bin/mocp -Q "**%ct/%tt**")
				;;
		esac

		trackname=$(/usr/bin/mocp -Q "%artist - %album - %song")
	fi

	echo "$trackname - $status"
}

while true; do
	TIME=$(/usr/bin/date +'%a %F %T')
	VOL=$(/usr/bin/amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
	BATT=$(/usr/bin/acpi -b | cut -f2 -d, | sed 's/ //g')
	MUSIC=$(currentmusic)

	/usr/bin/xsetroot -name "$MUSIC :: $VOL :: $BATT :: $TIME"
	sleep 1
done &

exec dwm
